<?php
if ( $a == 'a' && $b == 'a' && $c == 'a' ) { $am_cat = 151; }
if ( $a == 'b' && $b == 'a' && $c == 'a' ) { $am_cat = 152; }
if ( $a == 'c' && $b == 'a' && $c == 'a' ) { $am_cat = 153; }
if ( $a == 'd' && $b == 'a' && $c == 'a' ) { $am_cat = 154; }
if ( $a == 'e' && $b == 'a' && $c == 'a' ) { $am_cat = 155; }
if ( $a == 'f' && $b == 'a' && $c == 'a' ) { $am_cat = 156; }
if ( $a == 'g' && $b == 'a' && $c == 'a' ) { $am_cat = 157; }
if ( $a == 'h' && $b == 'a' && $c == 'a' ) { $am_cat = 158; }

if ( $a == 'a' && $b == 'b' && $c == 'a' ) { $am_cat = 159; }
if ( $a == 'a' && $b == 'c' && $c == 'a' ) { $am_cat = 160; }
if ( $a == 'b' && $b == 'b' && $c == 'a' ) { $am_cat = 161; }
if ( $a == 'b' && $b == 'c' && $c == 'a' ) { $am_cat = 162; }
if ( $a == 'c' && $b == 'b' && $c == 'a' ) { $am_cat = 163; }
if ( $a == 'c' && $b == 'c' && $c == 'a' ) { $am_cat = 164; }
if ( $a == 'd' && $b == 'b' && $c == 'a' ) { $am_cat = 165; }
if ( $a == 'd' && $b == 'c' && $c == 'a' ) { $am_cat = 166; }
if ( $a == 'e' && $b == 'b' && $c == 'a' ) { $am_cat = 167; }
if ( $a == 'e' && $b == 'c' && $c == 'a' ) { $am_cat = 168; }
if ( $a == 'f' && $b == 'b' && $c == 'a' ) { $am_cat = 169; }
if ( $a == 'f' && $b == 'c' && $c == 'a' ) { $am_cat = 170; }
if ( $a == 'g' && $b == 'b' && $c == 'a' ) { $am_cat = 171; }
if ( $a == 'g' && $b == 'c' && $c == 'a' ) { $am_cat = 172; }
if ( $a == 'h' && $b == 'b' && $c == 'a' ) { $am_cat = 173; }
if ( $a == 'h' && $b == 'c' && $c == 'a' ) { $am_cat = 174; }

if ( $a == 'a' && $b == 'a' && $c == 'b' ) { $am_cat = 175; }
if ( $a == 'a' && $b == 'a' && $c == 'c' ) { $am_cat = 176; }
if ( $a == 'b' && $b == 'a' && $c == 'b' ) { $am_cat = 177; }
if ( $a == 'b' && $b == 'a' && $c == 'c' ) { $am_cat = 178; }
if ( $a == 'c' && $b == 'a' && $c == 'b' ) { $am_cat = 179; }
if ( $a == 'c' && $b == 'a' && $c == 'c' ) { $am_cat = 180; }
if ( $a == 'd' && $b == 'a' && $c == 'b' ) { $am_cat = 181; }
if ( $a == 'd' && $b == 'a' && $c == 'c' ) { $am_cat = 182; }
if ( $a == 'e' && $b == 'a' && $c == 'b' ) { $am_cat = 183; }
if ( $a == 'e' && $b == 'a' && $c == 'c' ) { $am_cat = 184; }
if ( $a == 'f' && $b == 'a' && $c == 'b' ) { $am_cat = 185; }
if ( $a == 'f' && $b == 'a' && $c == 'c' ) { $am_cat = 186; }
if ( $a == 'g' && $b == 'a' && $c == 'b' ) { $am_cat = 187; }
if ( $a == 'g' && $b == 'a' && $c == 'c' ) { $am_cat = 188; }
if ( $a == 'h' && $b == 'a' && $c == 'b' ) { $am_cat = 189; }
if ( $a == 'h' && $b == 'a' && $c == 'c' ) { $am_cat = 190; }

if ( $a == 'a' && $b == 'b' && $c == 'b' ) { $am_cat = 191; }
if ( $a == 'a' && $b == 'b' && $c == 'c' ) { $am_cat = 192; }
if ( $a == 'b' && $b == 'b' && $c == 'b' ) { $am_cat = 193; }
if ( $a == 'b' && $b == 'b' && $c == 'c' ) { $am_cat = 194; }
if ( $a == 'c' && $b == 'b' && $c == 'b' ) { $am_cat = 195; }
if ( $a == 'c' && $b == 'b' && $c == 'c' ) { $am_cat = 196; }
if ( $a == 'd' && $b == 'b' && $c == 'b' ) { $am_cat = 197; }
if ( $a == 'd' && $b == 'b' && $c == 'c' ) { $am_cat = 198; }
if ( $a == 'e' && $b == 'b' && $c == 'b' ) { $am_cat = 199; }
if ( $a == 'e' && $b == 'b' && $c == 'c' ) { $am_cat = 200; }
if ( $a == 'f' && $b == 'b' && $c == 'b' ) { $am_cat = 201; }
if ( $a == 'f' && $b == 'b' && $c == 'c' ) { $am_cat = 202; }
if ( $a == 'g' && $b == 'b' && $c == 'b' ) { $am_cat = 203; }
if ( $a == 'g' && $b == 'b' && $c == 'c' ) { $am_cat = 204; }
if ( $a == 'h' && $b == 'b' && $c == 'b' ) { $am_cat = 205; }
if ( $a == 'h' && $b == 'b' && $c == 'c' ) { $am_cat = 206; }

if ( $a == 'a' && $b == 'c' && $c == 'b' ) { $am_cat = 207; }
if ( $a == 'a' && $b == 'c' && $c == 'c' ) { $am_cat = 208; }
if ( $a == 'b' && $b == 'c' && $c == 'b' ) { $am_cat = 209; }
if ( $a == 'b' && $b == 'c' && $c == 'c' ) { $am_cat = 210; }
if ( $a == 'c' && $b == 'c' && $c == 'b' ) { $am_cat = 211; }
if ( $a == 'c' && $b == 'c' && $c == 'c' ) { $am_cat = 212; }
if ( $a == 'd' && $b == 'c' && $c == 'b' ) { $am_cat = 213; }
if ( $a == 'd' && $b == 'c' && $c == 'c' ) { $am_cat = 214; }
if ( $a == 'e' && $b == 'c' && $c == 'b' ) { $am_cat = 215; }
if ( $a == 'e' && $b == 'c' && $c == 'c' ) { $am_cat = 216; }
if ( $a == 'f' && $b == 'c' && $c == 'b' ) { $am_cat = 217; }
if ( $a == 'f' && $b == 'c' && $c == 'c' ) { $am_cat = 218; }
if ( $a == 'g' && $b == 'c' && $c == 'b' ) { $am_cat = 219; }
if ( $a == 'g' && $b == 'c' && $c == 'c' ) { $am_cat = 220; }
if ( $a == 'h' && $b == 'c' && $c == 'b' ) { $am_cat = 221; }
if ( $a == 'h' && $b == 'c' && $c == 'c' ) { $am_cat = 222; }
?>